# Generated by Django 4.2.6 on 2023-10-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ColleageListDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("colleage_name", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("district", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("pincode", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("contact_num", models.IntegerField()),
            ],
        ),
    ]
