# Generated by Django 4.2.6 on 2023-10-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ColleageListApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="colleagelistdb",
            name="country",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
